apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patchesStrategicMerge:
  - deployments.yaml
resources:
  - secrets.yaml
  - secrets-agents.yaml
  - secrets-cred-manager.yaml
components:
  - ../components/github-organization
  - ../components/github-oauth
configMapGenerator:
  - name: jenkins-gke-plugins
    files:
      - configuration/plugins.txt
  - name: jenkins-gke-customization
    files:
      - configuration/groovy/1-set-url.groovy
      - configuration/groovy/2-add-gh-server.groovy
      - configuration/groovy/3-set-global-colors.groovy
  - name: jenkins-url
    envs:
      - env/jenkins-url.env
  - name: github-organization-plugin
    envs:
     - env/github-organization-plugin.env
  - name: github-oauth-plugin
    envs:
      - env/github-oauth-plugin.env
namespace: jenkins-example
