apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patchesStrategicMerge:
  - deployments.yaml
resources:
  - secrets.yaml
components:
  - ../components/github-organization
  - ../components/github-oauth
configMapGenerator:
  - name: jenkins-example-customization
    files:
      - configuration/groovy/set-url.groovy
  - name: github-organization-name
    envs:
     - github-organization-name.env
  - name: github-auth-details
    envs:
      - github-auth-details.env
namespace: jenkins-example
